services:
  penny:
    volumes:
      - ./penny/penny:/penny/penny
      - ./penny/pyproject.toml:/penny/pyproject.toml

  team:
    build:
      context: .
      dockerfile: penny-team/Dockerfile
    profiles: [tools]
    entrypoint: []
    working_dir: /repo/penny-team
    volumes:
      - ./penny-team/penny_team:/repo/penny-team/penny_team
      - ./penny-team/tests:/repo/penny-team/tests
      - ./penny-team/pyproject.toml:/repo/penny-team/pyproject.toml
